<?php
/*
 * Copyright (c) 2021.
 */

namespace App\Form\Routing;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\ChoiceList\View\ChoiceGroupView;
use Symfony\Component\Form\ChoiceList\View\ChoiceView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class CompanyTreeType extends EntityType
{

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $optGroups = [];
        foreach ($view->vars['choices'] as $label => $choice) {
            if ($choice instanceof  ChoiceGroupView && !in_array($label, $optGroups)) {
                $optGroups[] = $label;
            }
        }
        foreach ($view->vars['choices'] as $k => $choice) {
            if ($choice instanceof ChoiceView && in_array($choice->label, $optGroups)) {
                unset($view->vars['choices'][$k]);
            }
        }
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}
